### PR TITLE
Add banner text section to home page web

### PR DESCRIPTION
**Pull request by haveanicedavid**
## Description
Related to: [regen-network/regen-registry#853](https://github.com/regen-network/regen-web/pull/853)

Schema changes to address some hacky solutions to homepage tweaks

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] added new items content to `./deskStructure.js`
- [x] go through ["Deploying to production" instructions](https://github.com/regen-network/regen-sanity/blob/main/README.md#deploying-to-production) after this PR (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by mhagel — APPROVED** [review]
I haven't done sanity in a while. Don't you have to run some sort of schema update script? Or is that just for the environment..

**Comment by haveanicedavid** [comment]
@mhagel correct - I initially pulled in the production data (`yarn import-production`) to make sure the staging dataset was up to date with prod, then ran `yarn deploy-graphql` which deploys to the staging dataset (for local dev + production previews). 

Once this is merged, i'll run `yarn deploy` which will promote the staging dataset to production (so the copy in the [deploy preview](https://deploy-preview-853--regen-website.netlify.app/) is included in the production code

**Review by blushi — COMMENTED** [review]
Maybe we could add a short description field to https://github.com/regen-network/regen-sanity/blob/ee29e1e7b55e71674b1d9f9f1a3fdbd2ede5c9f9/schemas/documents/www/sharedSections.js#L8 to inform content editors that this is not actually being used anymore or just comment it until we want to use it back again

**Comment by haveanicedavid** [comment]
@blushi it's still currently used in the `science` and `token` pages (which I overlooked with the original hacky approach), but I agree it could be worth itemizing that in the description - particularly for shared sections. Just updated:
image

**Review by blushi — APPROVED** [review]

**Pull request merged**
