### PR TITLE
Fix github workflow

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: https://github.com/regen-network/regen-registry/issues/727
See https://github.com/sanity-io/github-action-sanity/issues/5#issuecomment-925111283

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] added new items content to `./deskStructure.js`
- [ ] go through ["Deploying to production" instructions](../../README.md#deploying-to-production) after this PR (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [x] confirmed all author checklist items have been addressed
- [x] reviewed code correctness and readability
- [x] reviewed documentation is accurate
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@haveanicedavid This needs to be merged before your Sanity migration PR

**Review by haveanicedavid — APPROVED** [review]

**Comment by haveanicedavid** [comment]
LGTM

**Comment by haveanicedavid** [comment]
FYI @blushi the "deploying to production instructions" link in the checkbox list is dead for me. I'm going to go ahead and merge to make sure everything is fixed before i merge the sanity pr

**Comment by blushi** [comment]
@haveanicedavid Please check out fixed link in https://github.com/regen-network/regen-sanity/pull/10

**Pull request merged**
